version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"  # Optional: configure encoding
    volumes:
       - "${SHARED}/data/postgres-data:/data/postgres"
       - "${SHARED}/data/postgres:/var/lib/postgresql/data"
       - "${SHARED}/data/pgdata:/var/lib/postgresql/data/pgdata"      
    ports:
      - "${PORT}:5432"
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge   

volumes:
  shared: 
    driver: local