
## flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.schemas=public
quarkus.flyway.locations=classpath:db/migration

%dev.quarkus.datasource.devservices.show-logs=true
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=quarkus
quarkus.datasource.password=quarkus

#quarkus.datasource.reactive.url=postgresql:///your_database
quarkus.datasource.reactive.max-size=20

